#!/bin/bash
export SWIFT_PROJNAME="Jialin_demo2" # You will need NERSC staff to create one
# You will need to export nersc nim password, same with cori/edison login pw
echo $LOGNAME "is Your Swift Store Login Name"
if [ -z "$NIMPW" ]; then
	echo "You Need to Export Your NIM PW to variable NIMPW"	
else
	echo "Your NIM Password is your Swift Store Login Password"
	module load python
	module load hdf5-parallel/1.9.234
	#echo "Installing Python Swiftclient"
	#sleep 2
	#pip install python-swiftclient --user
	echo "Compiling Sci-Swift"
	sleep 2
	make
	echo "Configuring Openstack Swift and Python Environment"
	sleep 2
	source swift.config.nersc
	source python.config.nersc
	echo "You Can Now Test Sci-Swift with ./HDF5_Objects_create"
fi
